[package]
name = "gdrr_2bp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
indexmap = "1.9.0"
by_address = "1.0.4"
